@startuml architecture.puml

component core {
	package notes.core
	package notes.json
}

component jackson {
}

notes.json ..> jackson

component ui {
 	folder notes.ui
    folder notes.dataAccess
}

notes.ui ..> notes.core
notes.ui ..> notes.json

component javafx {
 	component fxml {
 	}
}

ui ..> javafx
ui ..> fxml
notes.ui ..> notes.dataAccess


component rest {
	package notes.rest
}

notes.rest ..> notes.core

notes.rest ..> notes.json

@enduml
