@startuml architecture.puml

component core {
	package notes.core
	package notes.json
}

component jackson {
}

notes.json ..> jackson

component ui {
 	package notes.ui
}

notes.ui ..> notes.core
notes.ui ..> notes.json

component javafx {
 	component fxml {
 	}
}

ui ..> javafx
ui ..> fxml



@enduml
